server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://postgres.mkcrembkhtbpfxlmxhsc:74512275Cx%2C.22@aws-0-us-east-1.pooler.supabase.com:6543/postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true